language: python
sudo: false
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"
env:
 - DJANGO_VERSION=1.4
 - DJANGO_VERSION=1.6
 - DJANGO_VERSION=1.7
 - DJANGO_VERSION=1.8
install:
 - pip install -q "Django>=${DJANGO_VERSION},<${DJANGO_VERSION}.99" -r travis.txt
 - if [ "$DJANGO_VERSION" == "1.7" -o "$DJANGO_VERSION" == "1.8" ]; then pip install -q "jingo>=0.8"; fi
 - if [ "$DJANGO_VERSION" != "1.7" -a "$DJANGO_VERSION" != "1.8" ]; then pip install -q "jingo<0.8"; fi
script: ./run.sh test
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION=1.7
    - python: "2.6"
      env: DJANGO_VERSION=1.8
    - python: "3.3"
      env: DJANGO_VERSION=1.4
    - python: "3.4"
      env: DJANGO_VERSION=1.4
